[package]
name = "wm-common"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

wm-platform = { path = "../wm-platform" }
